---
common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: sidbase

development:
  database: sidbase_development
  password: sb1234
  <<: *common

test:
  database: sidbase_test
  password: sb1234
  min_messages: WARNING
  <<: *common

production:
  database: sidbase_production
  password: 
  <<: *common
